# -*- coding: utf-8 -*-
"""Project 3 Crop_Production.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c2YSeJNfmoFo3tO4L0JRFWzl2rgFwDCc
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import sklearn

"""#Data Gathering"""

crop_data=pd.read_csv("/content/Crop Production data.csv")

crop_data.head(6)

crop_data.columns

crop_data.info()

crop_data.describe()

"""# Data Preparation"""

# Identify the season, crop,year, state, district which are unique
season= crop_data['Season'].unique()
crop = crop_data['Crop'].unique()
state = crop_data['State_Name'].unique()
city= crop_data['District_Name'].unique()
crop_year = crop_data['Crop_Year'].unique()

print(f"Total no. of Seasons \t {len(season)} \n Seasons are \t {season}\n  \n")
print(f"Total no. of Crop \t {len(crop)} \n Crop are \t {crop}\n  \n")
print(f"Total no. of States \t {len(state)} \n States are \t {state}\n  \n")
print(f"Total no. of District \t {len(city)} \n Districts are \t {city}\n  \n")
print(f"Total no. of Crop_year \t {len(crop_year)} \n Year of Crop are \t {crop_year}\n  \n")

crop_data.isnull().sum()

crop_df = crop_data.dropna()

crop_df.isnull().sum()

"""#EDA"""

state_prod = {}
# Iterate over each state in the state list
for s in state:
    # Filter the DataFrame to get production values for the current state
    st_pd = crop_df[crop_df['State_Name'] == s]['Production']
    # Calculate the sum of production for the current state
    sum_production = st_pd.sum()
    # Store the total production for the current state in the dictionary
    state_prod[s] = sum_production

state_production = pd.DataFrame.from_dict(state_prod,  orient='index', columns=['Total Production'])
state_production

plt.figure(figsize=(30,8))
sns.barplot(x=state_prod.keys(), y=state_prod.values(), color = 'green', width = 0.3 )
plt.show()

#get top states which have high no. of production
top_states= state_production.sort_values(by='Total Production',ascending=False).head(5)
print(f"Top_States are : {top_states} ")

plt.figure(figsize=(10,5))
sns.barplot(x=crop_df['Crop_Year'], y=crop_df['Production'],palette='viridis',ci=None, align='center')
plt.xlabel('Crop Year')
plt.ylabel('Production')
plt.title('Crop Production Over Years')
plt.show()

plt.figure(figsize=(7,5))
sns.barplot(x= crop_df["Season"],y= crop_df["Production"], color='Green',ci=None)
plt.show()

crop_df.groupby("Season",axis=0).agg({"Production":np.sum})

#crop
crop_df['Crop'].value_counts()

#get top crops which have high no. of production
top_crop=crop_df.groupby("Crop")["Production"].sum().sort_values(ascending=False).head(5)
print(f"Top_crop are : {top_crop} ")

plt.figure(figsize=(7,5))
sns.barplot(x= top_crop.index,y= top_crop.values, color='Green')
plt.ylabel('Production')
plt.title('Production of top 5 crops')
plt.show()

"""## Goal of problem is to find the key insights for crop production & each crop production depends on various factors i.e. weather, area, region etc.

# Coconut
"""

#Analyse the Coconut crop patterns

#1. Make a dataframe for COCONUT data
coco_df = crop_df[crop_df['Crop']=='Coconut ']
coco_df.shape     #check the dimesion

coco_df.head(5)

#2. Analyse which season give mre production of COCONUT
plt.figure(figsize=(7,5))
sns.barplot(x= coco_df["Season"],y= coco_df["Production"], color='lightblue')
plt.title('Coconut Crop Production over Season')
plt.xlabel('Season')
plt.ylabel('Production')
plt.show()

"""Insight : Coconut grow whole year"""

#3. Which State give more coconut production
plt.figure(figsize=(7,5))
sns.barplot(x=coco_df["State_Name"], y=coco_df["Production"], color='blue', align='center',ci=None)
plt.xticks(rotation=90)
plt.title('Coconut Crop Production over State')
plt.xlabel('State')
plt.ylabel('Production')
plt.show()

"""Insights: Kerala have higher coconut production"""

#4. top district of india which have high coconut production
top_coco_dis=coco_df.groupby("District_Name")["Production"].sum().sort_values(ascending=False).head(10)
pd.DataFrame(top_coco_dis)

"""Insight : Kozhikode, Malappuram, Thirvananthapuram, Thrissur, Kannpur are the district which produce high coconut crop"""

#5. Which year give more coconut production
plt.figure(figsize=(7,5))
sns.barplot(x=coco_df["Crop_Year"], y=coco_df["Production"],palette='viridis',ci=None, align='center')
#plt.bar(x=coco_df["Crop_Year"], height=coco_df["Production"], color='lightgreen')
plt.xticks(rotation=90)
plt.title('Coconut Crop Production over year')
plt.xlabel('State')
plt.ylabel('Production')
plt.show()

#6. Calculate productivity (production per hectare)
coco_df['Productivity (tonnes/hectare)'] = coco_df['Production'] / coco_df['Area']

# Rank crops by productivity (from highest to lowest)
coco_df_ranked = coco_df.sort_values(by='Productivity (tonnes/hectare)', ascending=False)

# Display results
print("Ranked Crops by Productivity: \n \n")
coco_df_ranked.head(5)

"""## Key Insights for Coconut Crop:
1. Coconut grow whole year
2. Kerala have higher coconut production
3. In Birbhum(west bengal) have high crop productivity across india, that means this arae have high soil fertality for coconut
4. Birbhum also have high productivity rate (tone/hect.)
5. From 2011 to 2015 there is huge growth of coconut so in that years demand of coconut got increased

# Sugarcane
"""

#Analyse the Sugarcane crop patterns

#1. Make a dataframe for SUGARCANE data
sugar_df = crop_df[crop_df['Crop']=='Sugarcane']
sugar_df.shape     #check the dimesion

sugar_df.head()

#2. Analyse which season give more production of SUGARCANE
plt.figure(figsize=(7,5))
sns.barplot(x= sugar_df["Season"],y= sugar_df["Production"], ci = None,color='lightgreen')
plt.title('Sugarcane Crop Production over Season')
plt.xlabel('Season')
plt.ylabel('Production')
plt.show()

"""Insight: Suagarcane is grow more at Kharif season i.e. from month July to october"""

#3. Which State give more SUGARCANE production
plt.figure(figsize=(8,5))
sns.barplot(x=sugar_df["State_Name"], y=sugar_df["Production"], palette='husl', align='center', ci=None)
plt.xticks(rotation=90)
plt.title('Sugarcane Crop Production over State')
plt.xlabel('State')
plt.ylabel('Production')
plt.show()

"""Insight : Sugarcane mainly grow at Maharastra, UP, Tamil Nadu i.e. it grow more at tropical & subtropical region"""

#4. top district of india which have high SUGARCANE production
top_sugar_dis=sugar_df.groupby("District_Name")["Production"].sum().sort_values(ascending=False).head(10)
pd.DataFrame(top_sugar_dis)

#5. Which year give more sugarcane production
plt.figure(figsize=(7,5))
sns.barplot(x=sugar_df["Crop_Year"], y=sugar_df["Production"],palette='viridis',ci=None, align='center')
plt.xticks(rotation=90)
plt.title('Sugarcane Crop Production over year')
plt.xlabel('State')
plt.ylabel('Production')
plt.show()

"""Insight : At 1997 there is huge growth of sugarcane but after 2000 its demand get reduced"""

#6. Calculate productivity (production per hectare)
sugar_df['Productivity (tonnes/hectare)'] = sugar_df['Production'] / sugar_df['Area']

# Rank crops by productivity (from highest to lowest)
sugar_df_ranked = sugar_df.sort_values(by='Productivity (tonnes/hectare)', ascending=False)

# Display results
print("Ranked Crops by Productivity: \n \n")
sugar_df_ranked.head(5)

"""## Key Insights for Sugarcane Crop:
1. Suagarcane is grow more at Kharif season
2. Sugarcane mainly grow at Maharastra
3. In Muzaffarnagar have high crop productivity across india.
4. At 1997 there is huge growth of sugarcane but after 2000 its demand get reduced

#Rice
"""

#Analyse the Rice crop patterns

#1. Make a dataframe for Rice data
rice_df = crop_df[crop_df['Crop']=='Rice']
rice_df.shape     #check the dimesion
rice_df.head()

#2. Analyse which season give more production of Rice
plt.figure(figsize=(5,3))
sns.barplot(x= rice_df["Season"],y= rice_df["Production"], ci = None,color='#FF9801')
plt.title('Rice Crop Production over Season')
plt.xlabel('Season')
plt.ylabel('Production')
plt.show()

#3. Which State give more rice production
plt.figure(figsize=(8,5))
sns.barplot(x=rice_df["State_Name"], y=rice_df["Production"], palette='husl', align='center', ci=None)
plt.xticks(rotation=90)
plt.title('Rice Crop Production over State')
plt.xlabel('State')
plt.ylabel('Production')
plt.show()

#4. top district of india which have high rice production
top_rice_dis=rice_df.groupby("District_Name")["Production"].sum().sort_values(ascending=False).head(10)
pd.DataFrame(top_rice_dis)

#5. Which year give more rice production
plt.figure(figsize=(7,5))
sns.barplot(x=rice_df["Crop_Year"], y=rice_df["Production"],palette='flare',ci=None, align='center')
plt.xticks(rotation=90)
plt.title('Rice Crop Production over year')
plt.xlabel('State')
plt.ylabel('Production')
plt.show()

#6. Calculate productivity (production per hectare)
rice_df['Productivity (tonnes/hectare)'] = rice_df['Production'] / rice_df['Area']

# Rank crops by productivity (from highest to lowest)
rice_df_ranked = rice_df.sort_values(by='Productivity (tonnes/hectare)', ascending=False)

# Display results
print("Ranked Crops by Productivity: \n \n")
rice_df_ranked.head(5)

"""## Key Insights for Rice Crop:
1. Rice is grow more at Winter season
2. Rice mainly grow at Punjab
3. In Bardhaman have high crop productivity across india.
4. With the passage of time Rice Production incease i.e. demand increases

#Wheat
"""

#Analyse the Wheat crop patterns

#1. Make a dataframe for WHEAT data
wheat_df = crop_df[crop_df['Crop']=='Wheat']
wheat_df.shape     #check the dimesion
wheat_df.head()

#2. Analyse which season give more production of Wheat
plt.figure(figsize=(7,5))
sns.barplot(x= wheat_df["Season"],y= wheat_df["Production"], ci = None,color='green')
plt.title('Wheat Crop Production over Season')
plt.xlabel('Season')
plt.ylabel('Production')
plt.show()

#3. Which State give more WHEAT production
plt.figure(figsize=(8,5))
sns.barplot(x=wheat_df["State_Name"], y=wheat_df["Production"], palette='icefire', align='center', ci=None)
plt.xticks(rotation=90)
plt.title('Wheat Crop Production over State')
plt.xlabel('State')
plt.ylabel('Production')
plt.show()

#4. top district of india which have high Wheat production
top_wheat_dis=wheat_df.groupby("District_Name")["Production"].sum().sort_values(ascending=False).head(10)
pd.DataFrame(top_wheat_dis)

#5. Which year give more WHEAT production
plt.figure(figsize=(7,5))
sns.barplot(x=wheat_df["Crop_Year"], y=wheat_df["Production"],palette='YlOrBr',ci=None, align='center')
plt.xticks(rotation=90)
plt.title('Wheat Crop Production over year')
plt.xlabel('State')
plt.ylabel('Production')
plt.show()

#6. Calculate productivity (production per hectare)
wheat_df['Productivity (tonnes/hectare)'] = wheat_df['Production'] / wheat_df['Area']

# Rank crops by productivity (from highest to lowest)
wheat_df_ranked = wheat_df.sort_values(by='Productivity (tonnes/hectare)', ascending=False)

# Display results
print("Ranked Crops by Productivity: \n \n")
wheat_df_ranked.head(5)

"""## Key Insights for WHEAT Crop:
1. Wheat is grow more at Rabi season
2. It mainly grow at Punjab
3. In Firozepur have high crop productivity across india.
4. With the passage of time Wheat Production incease i.e. demand increases

# Potato
"""

#Analyse the Potato crop patterns

#1. Make a dataframe for POTATO data
potato_df = crop_df[crop_df['Crop']=='Potato']
potato_df.shape     #check the dimesion
potato_df.head()

#2. Analyse which season give more production of Potato
plt.figure(figsize=(7,5))
sns.barplot(x= potato_df["Season"],y= potato_df["Production"], ci = None,color='#AA4060')
plt.title('Potato Crop Production over Season')
plt.xlabel('Season')
plt.ylabel('Production')
plt.show()

#3. Which State give more potato production
plt.figure(figsize=(8,5))
sns.barplot(x= potato_df["State_Name"], y=potato_df["Production"], palette='crest', align='center', ci=None)
plt.xticks(rotation=90)
plt.title('Poatato Crop Production over State')
plt.xlabel('State')
plt.ylabel('Production')
plt.show()

#4. top district of india which have high coconut production
top_potato_dis=potato_df.groupby("District_Name")["Production"].sum().sort_values(ascending=False).head(10)
pd.DataFrame(top_potato_dis)

#5. Which year give more Potato production
plt.figure(figsize=(7,5))
sns.barplot(x=potato_df["Crop_Year"], y=potato_df["Production"],palette='flare',ci=None, align='center')
plt.xticks(rotation=90)
plt.title('Potato Crop Production over year')
plt.xlabel('State')
plt.ylabel('Production')
plt.show()

#6. Calculate productivity (production per hectare)
potato_df['Productivity (tonnes/hectare)'] = potato_df['Production'] / potato_df['Area']

# Rank crops by productivity (from highest to lowest)
potato_df_ranked = potato_df.sort_values(by='Productivity (tonnes/hectare)', ascending=False)

# Display results
print("Ranked Crops by Productivity: \n \n")
potato_df_ranked.head(5)

"""## Key Insights for Rice Crop:
1. Potato is grow more at Rabi season
2. It mainly grow at West Bengal
3. In Hooghly have high crop productivity across india.
4. From 2009 to 2014, potato production touches the peak.

#Feature Selection
"""

crop_df2=crop_df[['State_Name','Season','Crop','Area','Production']]

"""# Train Test Split"""

#one-hot encoding
crop_df_dum = pd.get_dummies(crop_df2)   #convert categorical variables into a set of dummy/indicator variables
crop_df_dum

x=crop_df_dum.drop(['Production'], axis=1)      #disrict_name doesn't play any more significant role so remove it
y=crop_df_dum[['Production']]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

"""## Feature scaling"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

"""# Data Modeling"""

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

# Random Forest
rf = RandomForestRegressor(random_state=42)
rf.fit(x_train_scaled, y_train)

# Gradient Boosting
gb = GradientBoostingRegressor(random_state=42)
gb.fit(x_train_scaled, y_train)

#Decision tree
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(random_state=30)
dt.fit(x_train , y_train)

y_pred=dt.predict(x_test)

"""#Evaluation"""

yr_pred = rf.predict(x_test_scaled)
from sklearn.metrics import r2_score
rRF = r2_score(y_test,yr_pred)            # R2 score shows the goodness fit of model into data
print("R2score for Random Forest is ",rRF)

yg_pred = rf.predict(x_test_scaled)
rGB = r2_score(y_test,yg_pred)            # R2 score shows the goodness fit of model into data
print("R2score for gradient boosting is ",rGB)

rDT = r2_score(y_test,y_pred)            # R2 score shows the goodness fit of model into data
print("R2score for gradient boosting is ",rDT)

"""Both gradient boosting & random forest model have equal R2 score but decision tree have less score,so we can go with either random forest or gradient booster model

# Insights

## Key Factors that Influence Crop Production

**Key Factors in Crop Production:**

**Seasonality:** Potatoes are primarily grown in the Rabi season, whereas sugarcane thrives in the Kharif season.


**Geographical Location :** Wheat agriculture thrives in areas such as Punjab due to suitable soil and climate conditions, but coconut cultivation is common in Kerala's tropical climate.

**Production Hotspots:** The Hooghly area in West Bengal is well-known for its high production in potato growing, reflecting good environmental conditions and effective farming practices.

**Historical Production Trends:**Rice output has continuously increased throughout time, reflecting advances in agricultural practices, seed varieties, and irrigation systems.

**Demand Dynamics:** The late 1990s boom in sugarcane production was driven by increased demand from the sugar sector, whereas swings in potato prices cause farmers to modify their production levels.

**Yield Improvement:**The use of high-yielding rice varieties and contemporary farming practices has resulted in large increases in rice yield per hectare, which contributes to increased overall production.

**Growth Factors:** Soil fertility and moisture levels in areas such as Bardhaman help to create favorable circumstances for rice growth, while good pest management measures assure low crop loss.

**Market Trends:** Monitoring market trends indicates swings in potato prices, prompting farmers to modify production levels and crop rotation plans to maximize profits.

**Government Policies and Support:** Government subsidies for wheat growing in Punjab encourage farmers to use modern agricultural practices and invest in high-quality inputs, resulting in higher production and income levels.


***Through this factor we can make informed decisions, and also to pedict crop production for a specific we go further with Regression model either Random Forest Regressor or Gradient Booster Technique***
"""

